# Keith Rausch

import numpy as np
import matplotlib.pyplot as plt
import json, base64
import os

import tdoa_algos as tdoa
from plotting_utils import plot_points, plot_half_hyperbolas
from chatgpt_example_dds import generate_scene


def screen_info():
    screen_width_inches = 19.2 
    screen_height_inches = 10.8
    dpi_value = 100
    return screen_height_inches, screen_width_inches, dpi_value


def new_fig():
    screen_height_inches, screen_width_inches, _ = screen_info()
    fig = plt.figure(figsize=(screen_width_inches, screen_height_inches))
    return fig

def save_fig(fig, save_name):
    _, _, dpi_value = screen_info()
    fig.savefig(save_name, dpi=dpi_value, bbox_inches='tight', pad_inches=0)

def plot_points_with_labels(ax, receivers, emitters, system):
    plot_points(ax, 
                system.candidate_receivers,
                system.candidate_emitters,
                color='blue',
                receiver_marker='.',
                emitter_marker='*',
                legend_label='estimated')
    plot_points(ax, 
                receivers,
                emitters,
                color='red',
                receiver_marker='o',
                emitter_marker='x',
                legend_label='truth')


def test_math_and_render(n_receivers = 4, n_emitters=6, speed_of_sound = 1, n_dimensions=2):

    # np.random.seed(9001)
    # receivers = np.random.rand(n_dimensions, n_receivers) * 5 - 2.5
    # emitters = np.random.rand(n_dimensions, n_emitters) * 10 - 5

    np.random.seed(0)
    receivers, emitters = generate_scene(num_mics = n_receivers, num_sources = n_emitters, dims = n_dimensions)
    receivers = receivers.T
    emitters = emitters.T

    # emitter_pairs = [(i*2, i*2+1) for i in range(n_emitters//2)] # [(0,1), (2,3), (4,5), ...]
    emitter_pairs = [(i, (i+1) % n_emitters) for i in range(n_emitters)] # [(0,1), (1,2), (2,3), ...]
    # [(0,1), (0,2), ..., (1,2), (1,3), ...]
    # emitter_pairs = []
    # for e_A in range(n_emitters):
    #     for e_B in range(e_A+1, n_emitters):
    #         emitter_pairs.append((e_A, e_B))

    # apply constraints
    receivers, emitters, _, _ = tdoa.global_constraints(receivers, emitters, verbose=True)
    receivers, emitters = tdoa.TDOASystemSVD._check_for_reflections(receivers, emitters, dims=n_dimensions)

    # compute time differences of arrival
    delta_times_r, delta_times_e = tdoa.delta_times_from_points(receivers,
                                                                emitters,
                                                                emitter_pairs,
                                                                speed_of_sound=speed_of_sound)
    
    compute_residuals = lambda rcvs, emtrs: np.concatenate([receivers, emitters], axis=-1) - np.concatenate([rcvs, emtrs], axis=-1)

    # perform the magic
    # system = tdoa.TDOASystem()
    system = tdoa.TDOASystemSVD()
    system.initialize(n_receivers=n_receivers,
                      n_emitters=n_emitters,
                      n_dimensions=n_dimensions,
                      speed_of_sound=speed_of_sound)
    
    system.calibrate(delta_times_r,
                     delta_times_e,
                     emitter_pairs)

    residuals = compute_residuals(system.candidate_receivers, system.candidate_emitters)
    # residuals_mag = np.sqrt(np.sum(residuals*residuals))
    residuals_mean = np.mean(np.abs(residuals))
    if residuals_mean < 1E-3:
        print(f"SUCCESS. mean_residual: {residuals_mean}")
    else:
        print(f"failed. mean_residual: {residuals_mean}")

    #
    #
    # plot all results
    #
    #


    #
    # loci generated by true receiver / emitter points
    #
    fig = new_fig()
    ax = fig.add_subplot(111)
    if n_dimensions == 3:
        ax = fig.subplots(subplot_kw={"projection": "3d"})
    ax.set_title(f'loci generated by true receivers and emitters ({n_dimensions}d)')
    plot_half_hyperbolas(ax, 
                         delta_times_e,
                         emitters,
                         receivers,
                         hyperbola_colors='--k',
                         label_string='e{}-e{},r{}',
                         speed_of_sound=speed_of_sound,
                         legend_label='receiver locus')
    plot_half_hyperbolas(ax, 
                         delta_times_r,
                         receivers,
                         emitters,
                         hyperbola_colors='--g',
                         speed_of_sound=speed_of_sound,
                         legend_label='emitter locus')
    plot_points_with_labels(ax, receivers, emitters, system)

    if len(system.receiver_history) > 0:
        for r in range(n_receivers):
            ax.plot(*(np.array([receiver[:,r] for receiver in system.receiver_history]).T), 
                    linestyle=':', 
                    color='y', 
                    label=('solver history' if r==0 else None))
    if len(system.emitter_history):
        for e in range(n_emitters):
            ax.plot(*(np.array([emitter[:,e] for emitter in system.emitter_history]).T), 
                    linestyle=':', 
                    color='y', 
                    label=None)

    ax.legend()
    save_fig(fig, f'loci_from_truth_points_{n_dimensions}d.png')

    #
    # loci generated by estimated receiver / emitter points
    #
    fig = new_fig()
    ax = fig.add_subplot(111)
    if n_dimensions == 3:
        ax = fig.subplots(subplot_kw={"projection": "3d"})
    ax.set_title(f'loci generated by estimated receivers and emitters ({n_dimensions}d)')
    plot_half_hyperbolas(ax,
                         delta_times_e,
                         system.candidate_emitters,
                         system.candidate_receivers,
                         hyperbola_colors='--b',
                         label_string='e{}-e{},r{}',
                         speed_of_sound=speed_of_sound,
                         legend_label='receiver locus')
    plot_half_hyperbolas(ax,
                         delta_times_r,
                         system.candidate_receivers,
                         system.candidate_emitters,
                         hyperbola_colors='--y',
                         speed_of_sound=speed_of_sound,
                         legend_label='emitter locus')
    plot_points_with_labels(ax, receivers, emitters, system)

    ax.legend()
    save_fig(fig, f'loci_from_estimated_points_{n_dimensions}d.png')
    
    print()



if __name__ == "__main__":
    test_math_and_render(n_receivers = 4, n_emitters = 6, speed_of_sound = 343, n_dimensions=2)
    test_math_and_render(n_receivers = 6, n_emitters = 7, speed_of_sound = 343, n_dimensions=3)
    plt.show()