// source: commands.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
goog.exportSymbol('proto.commands.AddTodoClass', null, global);
goog.exportSymbol('proto.commands.CMD_Header', null, global);
goog.exportSymbol('proto.commands.CMD_Holder', null, global);
goog.exportSymbol('proto.commands.CMD_Payload', null, global);
goog.exportSymbol('proto.commands.CMD_Payload.VariantCase', null, global);
goog.exportSymbol('proto.commands.CMD_Response', null, global);
goog.exportSymbol('proto.commands.FullStateEstimate', null, global);
goog.exportSymbol('proto.commands.MockSimulation', null, global);
goog.exportSymbol('proto.commands.PingClass', null, global);
goog.exportSymbol('proto.commands.PointCloud', null, global);
goog.exportSymbol('proto.commands.TLM_HK', null, global);
goog.exportSymbol('proto.commands.TLM_Header', null, global);
goog.exportSymbol('proto.commands.TLM_Holder', null, global);
goog.exportSymbol('proto.commands.TLM_Payload', null, global);
goog.exportSymbol('proto.commands.TLM_Payload.VariantCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.commands.PointCloud = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.commands.PointCloud.repeatedFields_, null);
};
goog.inherits(proto.commands.PointCloud, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.commands.PointCloud.displayName = 'proto.commands.PointCloud';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.commands.AddTodoClass = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.commands.AddTodoClass, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.commands.AddTodoClass.displayName = 'proto.commands.AddTodoClass';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.commands.PingClass = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.commands.PingClass, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.commands.PingClass.displayName = 'proto.commands.PingClass';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.commands.FullStateEstimate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.commands.FullStateEstimate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.commands.FullStateEstimate.displayName = 'proto.commands.FullStateEstimate';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.commands.MockSimulation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.commands.MockSimulation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.commands.MockSimulation.displayName = 'proto.commands.MockSimulation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.commands.CMD_Header = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.commands.CMD_Header, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.commands.CMD_Header.displayName = 'proto.commands.CMD_Header';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.commands.CMD_Payload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.commands.CMD_Payload.oneofGroups_);
};
goog.inherits(proto.commands.CMD_Payload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.commands.CMD_Payload.displayName = 'proto.commands.CMD_Payload';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.commands.CMD_Holder = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.commands.CMD_Holder, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.commands.CMD_Holder.displayName = 'proto.commands.CMD_Holder';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.commands.CMD_Response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.commands.CMD_Response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.commands.CMD_Response.displayName = 'proto.commands.CMD_Response';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.commands.TLM_HK = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.commands.TLM_HK, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.commands.TLM_HK.displayName = 'proto.commands.TLM_HK';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.commands.TLM_Header = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.commands.TLM_Header, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.commands.TLM_Header.displayName = 'proto.commands.TLM_Header';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.commands.TLM_Payload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.commands.TLM_Payload.oneofGroups_);
};
goog.inherits(proto.commands.TLM_Payload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.commands.TLM_Payload.displayName = 'proto.commands.TLM_Payload';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.commands.TLM_Holder = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.commands.TLM_Holder, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.commands.TLM_Holder.displayName = 'proto.commands.TLM_Holder';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.commands.PointCloud.repeatedFields_ = [1,2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.commands.PointCloud.prototype.toObject = function(opt_includeInstance) {
  return proto.commands.PointCloud.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.commands.PointCloud} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.PointCloud.toObject = function(includeInstance, msg) {
  var f, obj = {
    xCoordsList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 1)) == null ? undefined : f,
    yCoordsList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 2)) == null ? undefined : f,
    zCoordsList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.commands.PointCloud}
 */
proto.commands.PointCloud.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.commands.PointCloud;
  return proto.commands.PointCloud.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.commands.PointCloud} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.commands.PointCloud}
 */
proto.commands.PointCloud.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addXCoords(values[i]);
      }
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addYCoords(values[i]);
      }
      break;
    case 3:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addZCoords(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.commands.PointCloud.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.commands.PointCloud.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.commands.PointCloud} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.PointCloud.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getXCoordsList();
  if (f.length > 0) {
    writer.writePackedFloat(
      1,
      f
    );
  }
  f = message.getYCoordsList();
  if (f.length > 0) {
    writer.writePackedFloat(
      2,
      f
    );
  }
  f = message.getZCoordsList();
  if (f.length > 0) {
    writer.writePackedFloat(
      3,
      f
    );
  }
};


/**
 * repeated float x_coords = 1;
 * @return {!Array<number>}
 */
proto.commands.PointCloud.prototype.getXCoordsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.commands.PointCloud} returns this
 */
proto.commands.PointCloud.prototype.setXCoordsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.commands.PointCloud} returns this
 */
proto.commands.PointCloud.prototype.addXCoords = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.commands.PointCloud} returns this
 */
proto.commands.PointCloud.prototype.clearXCoordsList = function() {
  return this.setXCoordsList([]);
};


/**
 * repeated float y_coords = 2;
 * @return {!Array<number>}
 */
proto.commands.PointCloud.prototype.getYCoordsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.commands.PointCloud} returns this
 */
proto.commands.PointCloud.prototype.setYCoordsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.commands.PointCloud} returns this
 */
proto.commands.PointCloud.prototype.addYCoords = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.commands.PointCloud} returns this
 */
proto.commands.PointCloud.prototype.clearYCoordsList = function() {
  return this.setYCoordsList([]);
};


/**
 * repeated float z_coords = 3;
 * @return {!Array<number>}
 */
proto.commands.PointCloud.prototype.getZCoordsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.commands.PointCloud} returns this
 */
proto.commands.PointCloud.prototype.setZCoordsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.commands.PointCloud} returns this
 */
proto.commands.PointCloud.prototype.addZCoords = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.commands.PointCloud} returns this
 */
proto.commands.PointCloud.prototype.clearZCoordsList = function() {
  return this.setZCoordsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.commands.AddTodoClass.prototype.toObject = function(opt_includeInstance) {
  return proto.commands.AddTodoClass.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.commands.AddTodoClass} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.AddTodoClass.toObject = function(includeInstance, msg) {
  var f, obj = {
    text: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.commands.AddTodoClass}
 */
proto.commands.AddTodoClass.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.commands.AddTodoClass;
  return proto.commands.AddTodoClass.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.commands.AddTodoClass} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.commands.AddTodoClass}
 */
proto.commands.AddTodoClass.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.commands.AddTodoClass.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.commands.AddTodoClass.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.commands.AddTodoClass} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.AddTodoClass.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string text = 1;
 * @return {string}
 */
proto.commands.AddTodoClass.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.commands.AddTodoClass} returns this
 */
proto.commands.AddTodoClass.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.commands.PingClass.prototype.toObject = function(opt_includeInstance) {
  return proto.commands.PingClass.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.commands.PingClass} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.PingClass.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.commands.PingClass}
 */
proto.commands.PingClass.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.commands.PingClass;
  return proto.commands.PingClass.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.commands.PingClass} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.commands.PingClass}
 */
proto.commands.PingClass.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.commands.PingClass.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.commands.PingClass.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.commands.PingClass} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.PingClass.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.commands.FullStateEstimate.prototype.toObject = function(opt_includeInstance) {
  return proto.commands.FullStateEstimate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.commands.FullStateEstimate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.FullStateEstimate.toObject = function(includeInstance, msg) {
  var f, obj = {
    trueReceivers: (f = msg.getTrueReceivers()) && proto.commands.PointCloud.toObject(includeInstance, f),
    trueEmitters: (f = msg.getTrueEmitters()) && proto.commands.PointCloud.toObject(includeInstance, f),
    estReceivers: (f = msg.getEstReceivers()) && proto.commands.PointCloud.toObject(includeInstance, f),
    estEmitters: (f = msg.getEstEmitters()) && proto.commands.PointCloud.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.commands.FullStateEstimate}
 */
proto.commands.FullStateEstimate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.commands.FullStateEstimate;
  return proto.commands.FullStateEstimate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.commands.FullStateEstimate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.commands.FullStateEstimate}
 */
proto.commands.FullStateEstimate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.commands.PointCloud;
      reader.readMessage(value,proto.commands.PointCloud.deserializeBinaryFromReader);
      msg.setTrueReceivers(value);
      break;
    case 2:
      var value = new proto.commands.PointCloud;
      reader.readMessage(value,proto.commands.PointCloud.deserializeBinaryFromReader);
      msg.setTrueEmitters(value);
      break;
    case 3:
      var value = new proto.commands.PointCloud;
      reader.readMessage(value,proto.commands.PointCloud.deserializeBinaryFromReader);
      msg.setEstReceivers(value);
      break;
    case 4:
      var value = new proto.commands.PointCloud;
      reader.readMessage(value,proto.commands.PointCloud.deserializeBinaryFromReader);
      msg.setEstEmitters(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.commands.FullStateEstimate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.commands.FullStateEstimate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.commands.FullStateEstimate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.FullStateEstimate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTrueReceivers();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.commands.PointCloud.serializeBinaryToWriter
    );
  }
  f = message.getTrueEmitters();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.commands.PointCloud.serializeBinaryToWriter
    );
  }
  f = message.getEstReceivers();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.commands.PointCloud.serializeBinaryToWriter
    );
  }
  f = message.getEstEmitters();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.commands.PointCloud.serializeBinaryToWriter
    );
  }
};


/**
 * optional PointCloud true_receivers = 1;
 * @return {?proto.commands.PointCloud}
 */
proto.commands.FullStateEstimate.prototype.getTrueReceivers = function() {
  return /** @type{?proto.commands.PointCloud} */ (
    jspb.Message.getWrapperField(this, proto.commands.PointCloud, 1));
};


/**
 * @param {?proto.commands.PointCloud|undefined} value
 * @return {!proto.commands.FullStateEstimate} returns this
*/
proto.commands.FullStateEstimate.prototype.setTrueReceivers = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.commands.FullStateEstimate} returns this
 */
proto.commands.FullStateEstimate.prototype.clearTrueReceivers = function() {
  return this.setTrueReceivers(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.commands.FullStateEstimate.prototype.hasTrueReceivers = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional PointCloud true_emitters = 2;
 * @return {?proto.commands.PointCloud}
 */
proto.commands.FullStateEstimate.prototype.getTrueEmitters = function() {
  return /** @type{?proto.commands.PointCloud} */ (
    jspb.Message.getWrapperField(this, proto.commands.PointCloud, 2));
};


/**
 * @param {?proto.commands.PointCloud|undefined} value
 * @return {!proto.commands.FullStateEstimate} returns this
*/
proto.commands.FullStateEstimate.prototype.setTrueEmitters = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.commands.FullStateEstimate} returns this
 */
proto.commands.FullStateEstimate.prototype.clearTrueEmitters = function() {
  return this.setTrueEmitters(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.commands.FullStateEstimate.prototype.hasTrueEmitters = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional PointCloud est_receivers = 3;
 * @return {?proto.commands.PointCloud}
 */
proto.commands.FullStateEstimate.prototype.getEstReceivers = function() {
  return /** @type{?proto.commands.PointCloud} */ (
    jspb.Message.getWrapperField(this, proto.commands.PointCloud, 3));
};


/**
 * @param {?proto.commands.PointCloud|undefined} value
 * @return {!proto.commands.FullStateEstimate} returns this
*/
proto.commands.FullStateEstimate.prototype.setEstReceivers = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.commands.FullStateEstimate} returns this
 */
proto.commands.FullStateEstimate.prototype.clearEstReceivers = function() {
  return this.setEstReceivers(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.commands.FullStateEstimate.prototype.hasEstReceivers = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional PointCloud est_emitters = 4;
 * @return {?proto.commands.PointCloud}
 */
proto.commands.FullStateEstimate.prototype.getEstEmitters = function() {
  return /** @type{?proto.commands.PointCloud} */ (
    jspb.Message.getWrapperField(this, proto.commands.PointCloud, 4));
};


/**
 * @param {?proto.commands.PointCloud|undefined} value
 * @return {!proto.commands.FullStateEstimate} returns this
*/
proto.commands.FullStateEstimate.prototype.setEstEmitters = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.commands.FullStateEstimate} returns this
 */
proto.commands.FullStateEstimate.prototype.clearEstEmitters = function() {
  return this.setEstEmitters(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.commands.FullStateEstimate.prototype.hasEstEmitters = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.commands.MockSimulation.prototype.toObject = function(opt_includeInstance) {
  return proto.commands.MockSimulation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.commands.MockSimulation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.MockSimulation.toObject = function(includeInstance, msg) {
  var f, obj = {
    fullStateEstimate: (f = msg.getFullStateEstimate()) && proto.commands.FullStateEstimate.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.commands.MockSimulation}
 */
proto.commands.MockSimulation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.commands.MockSimulation;
  return proto.commands.MockSimulation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.commands.MockSimulation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.commands.MockSimulation}
 */
proto.commands.MockSimulation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.commands.FullStateEstimate;
      reader.readMessage(value,proto.commands.FullStateEstimate.deserializeBinaryFromReader);
      msg.setFullStateEstimate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.commands.MockSimulation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.commands.MockSimulation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.commands.MockSimulation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.MockSimulation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFullStateEstimate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.commands.FullStateEstimate.serializeBinaryToWriter
    );
  }
};


/**
 * optional FullStateEstimate full_state_estimate = 1;
 * @return {?proto.commands.FullStateEstimate}
 */
proto.commands.MockSimulation.prototype.getFullStateEstimate = function() {
  return /** @type{?proto.commands.FullStateEstimate} */ (
    jspb.Message.getWrapperField(this, proto.commands.FullStateEstimate, 1));
};


/**
 * @param {?proto.commands.FullStateEstimate|undefined} value
 * @return {!proto.commands.MockSimulation} returns this
*/
proto.commands.MockSimulation.prototype.setFullStateEstimate = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.commands.MockSimulation} returns this
 */
proto.commands.MockSimulation.prototype.clearFullStateEstimate = function() {
  return this.setFullStateEstimate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.commands.MockSimulation.prototype.hasFullStateEstimate = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.commands.CMD_Header.prototype.toObject = function(opt_includeInstance) {
  return proto.commands.CMD_Header.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.commands.CMD_Header} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.CMD_Header.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    objName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    cmdName: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.commands.CMD_Header}
 */
proto.commands.CMD_Header.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.commands.CMD_Header;
  return proto.commands.CMD_Header.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.commands.CMD_Header} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.commands.CMD_Header}
 */
proto.commands.CMD_Header.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setObjName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCmdName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.commands.CMD_Header.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.commands.CMD_Header.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.commands.CMD_Header} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.CMD_Header.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getObjName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCmdName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string request_id = 1;
 * @return {string}
 */
proto.commands.CMD_Header.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.commands.CMD_Header} returns this
 */
proto.commands.CMD_Header.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string obj_name = 2;
 * @return {string}
 */
proto.commands.CMD_Header.prototype.getObjName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.commands.CMD_Header} returns this
 */
proto.commands.CMD_Header.prototype.setObjName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string cmd_name = 3;
 * @return {string}
 */
proto.commands.CMD_Header.prototype.getCmdName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.commands.CMD_Header} returns this
 */
proto.commands.CMD_Header.prototype.setCmdName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.commands.CMD_Payload.oneofGroups_ = [[3,4,5]];

/**
 * @enum {number}
 */
proto.commands.CMD_Payload.VariantCase = {
  VARIANT_NOT_SET: 0,
  ADD_TODO_FIELD: 3,
  PING_FIELD: 4,
  START_MOCK_SIMULATION: 5
};

/**
 * @return {proto.commands.CMD_Payload.VariantCase}
 */
proto.commands.CMD_Payload.prototype.getVariantCase = function() {
  return /** @type {proto.commands.CMD_Payload.VariantCase} */(jspb.Message.computeOneofCase(this, proto.commands.CMD_Payload.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.commands.CMD_Payload.prototype.toObject = function(opt_includeInstance) {
  return proto.commands.CMD_Payload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.commands.CMD_Payload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.CMD_Payload.toObject = function(includeInstance, msg) {
  var f, obj = {
    addTodoField: (f = msg.getAddTodoField()) && proto.commands.AddTodoClass.toObject(includeInstance, f),
    pingField: (f = msg.getPingField()) && proto.commands.PingClass.toObject(includeInstance, f),
    startMockSimulation: (f = msg.getStartMockSimulation()) && proto.commands.MockSimulation.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.commands.CMD_Payload}
 */
proto.commands.CMD_Payload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.commands.CMD_Payload;
  return proto.commands.CMD_Payload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.commands.CMD_Payload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.commands.CMD_Payload}
 */
proto.commands.CMD_Payload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 3:
      var value = new proto.commands.AddTodoClass;
      reader.readMessage(value,proto.commands.AddTodoClass.deserializeBinaryFromReader);
      msg.setAddTodoField(value);
      break;
    case 4:
      var value = new proto.commands.PingClass;
      reader.readMessage(value,proto.commands.PingClass.deserializeBinaryFromReader);
      msg.setPingField(value);
      break;
    case 5:
      var value = new proto.commands.MockSimulation;
      reader.readMessage(value,proto.commands.MockSimulation.deserializeBinaryFromReader);
      msg.setStartMockSimulation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.commands.CMD_Payload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.commands.CMD_Payload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.commands.CMD_Payload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.CMD_Payload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddTodoField();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.commands.AddTodoClass.serializeBinaryToWriter
    );
  }
  f = message.getPingField();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.commands.PingClass.serializeBinaryToWriter
    );
  }
  f = message.getStartMockSimulation();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.commands.MockSimulation.serializeBinaryToWriter
    );
  }
};


/**
 * optional AddTodoClass add_todo_field = 3;
 * @return {?proto.commands.AddTodoClass}
 */
proto.commands.CMD_Payload.prototype.getAddTodoField = function() {
  return /** @type{?proto.commands.AddTodoClass} */ (
    jspb.Message.getWrapperField(this, proto.commands.AddTodoClass, 3));
};


/**
 * @param {?proto.commands.AddTodoClass|undefined} value
 * @return {!proto.commands.CMD_Payload} returns this
*/
proto.commands.CMD_Payload.prototype.setAddTodoField = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.commands.CMD_Payload.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.commands.CMD_Payload} returns this
 */
proto.commands.CMD_Payload.prototype.clearAddTodoField = function() {
  return this.setAddTodoField(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.commands.CMD_Payload.prototype.hasAddTodoField = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional PingClass ping_field = 4;
 * @return {?proto.commands.PingClass}
 */
proto.commands.CMD_Payload.prototype.getPingField = function() {
  return /** @type{?proto.commands.PingClass} */ (
    jspb.Message.getWrapperField(this, proto.commands.PingClass, 4));
};


/**
 * @param {?proto.commands.PingClass|undefined} value
 * @return {!proto.commands.CMD_Payload} returns this
*/
proto.commands.CMD_Payload.prototype.setPingField = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.commands.CMD_Payload.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.commands.CMD_Payload} returns this
 */
proto.commands.CMD_Payload.prototype.clearPingField = function() {
  return this.setPingField(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.commands.CMD_Payload.prototype.hasPingField = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional MockSimulation start_mock_simulation = 5;
 * @return {?proto.commands.MockSimulation}
 */
proto.commands.CMD_Payload.prototype.getStartMockSimulation = function() {
  return /** @type{?proto.commands.MockSimulation} */ (
    jspb.Message.getWrapperField(this, proto.commands.MockSimulation, 5));
};


/**
 * @param {?proto.commands.MockSimulation|undefined} value
 * @return {!proto.commands.CMD_Payload} returns this
*/
proto.commands.CMD_Payload.prototype.setStartMockSimulation = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.commands.CMD_Payload.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.commands.CMD_Payload} returns this
 */
proto.commands.CMD_Payload.prototype.clearStartMockSimulation = function() {
  return this.setStartMockSimulation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.commands.CMD_Payload.prototype.hasStartMockSimulation = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.commands.CMD_Holder.prototype.toObject = function(opt_includeInstance) {
  return proto.commands.CMD_Holder.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.commands.CMD_Holder} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.CMD_Holder.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && proto.commands.CMD_Header.toObject(includeInstance, f),
    payload: (f = msg.getPayload()) && google_protobuf_any_pb.Any.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.commands.CMD_Holder}
 */
proto.commands.CMD_Holder.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.commands.CMD_Holder;
  return proto.commands.CMD_Holder.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.commands.CMD_Holder} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.commands.CMD_Holder}
 */
proto.commands.CMD_Holder.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.commands.CMD_Header;
      reader.readMessage(value,proto.commands.CMD_Header.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setPayload(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.commands.CMD_Holder.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.commands.CMD_Holder.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.commands.CMD_Holder} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.CMD_Holder.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.commands.CMD_Header.serializeBinaryToWriter
    );
  }
  f = message.getPayload();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
};


/**
 * optional CMD_Header header = 1;
 * @return {?proto.commands.CMD_Header}
 */
proto.commands.CMD_Holder.prototype.getHeader = function() {
  return /** @type{?proto.commands.CMD_Header} */ (
    jspb.Message.getWrapperField(this, proto.commands.CMD_Header, 1));
};


/**
 * @param {?proto.commands.CMD_Header|undefined} value
 * @return {!proto.commands.CMD_Holder} returns this
*/
proto.commands.CMD_Holder.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.commands.CMD_Holder} returns this
 */
proto.commands.CMD_Holder.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.commands.CMD_Holder.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Any payload = 2;
 * @return {?proto.google.protobuf.Any}
 */
proto.commands.CMD_Holder.prototype.getPayload = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 2));
};


/**
 * @param {?proto.google.protobuf.Any|undefined} value
 * @return {!proto.commands.CMD_Holder} returns this
*/
proto.commands.CMD_Holder.prototype.setPayload = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.commands.CMD_Holder} returns this
 */
proto.commands.CMD_Holder.prototype.clearPayload = function() {
  return this.setPayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.commands.CMD_Holder.prototype.hasPayload = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.commands.CMD_Response.prototype.toObject = function(opt_includeInstance) {
  return proto.commands.CMD_Response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.commands.CMD_Response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.CMD_Response.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    success: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    message: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.commands.CMD_Response}
 */
proto.commands.CMD_Response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.commands.CMD_Response;
  return proto.commands.CMD_Response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.commands.CMD_Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.commands.CMD_Response}
 */
proto.commands.CMD_Response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.commands.CMD_Response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.commands.CMD_Response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.commands.CMD_Response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.CMD_Response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string request_id = 1;
 * @return {string}
 */
proto.commands.CMD_Response.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.commands.CMD_Response} returns this
 */
proto.commands.CMD_Response.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool success = 2;
 * @return {boolean}
 */
proto.commands.CMD_Response.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.commands.CMD_Response} returns this
 */
proto.commands.CMD_Response.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional string message = 3;
 * @return {string}
 */
proto.commands.CMD_Response.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.commands.CMD_Response} returns this
 */
proto.commands.CMD_Response.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.commands.TLM_HK.prototype.toObject = function(opt_includeInstance) {
  return proto.commands.TLM_HK.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.commands.TLM_HK} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.TLM_HK.toObject = function(includeInstance, msg) {
  var f, obj = {
    nClients: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.commands.TLM_HK}
 */
proto.commands.TLM_HK.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.commands.TLM_HK;
  return proto.commands.TLM_HK.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.commands.TLM_HK} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.commands.TLM_HK}
 */
proto.commands.TLM_HK.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setNClients(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.commands.TLM_HK.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.commands.TLM_HK.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.commands.TLM_HK} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.TLM_HK.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNClients();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
};


/**
 * optional uint64 n_clients = 1;
 * @return {number}
 */
proto.commands.TLM_HK.prototype.getNClients = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.commands.TLM_HK} returns this
 */
proto.commands.TLM_HK.prototype.setNClients = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.commands.TLM_Header.prototype.toObject = function(opt_includeInstance) {
  return proto.commands.TLM_Header.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.commands.TLM_Header} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.TLM_Header.toObject = function(includeInstance, msg) {
  var f, obj = {
    timeNs: jspb.Message.getFieldWithDefault(msg, 1, 0),
    topicType: jspb.Message.getFieldWithDefault(msg, 2, ""),
    topicName: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.commands.TLM_Header}
 */
proto.commands.TLM_Header.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.commands.TLM_Header;
  return proto.commands.TLM_Header.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.commands.TLM_Header} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.commands.TLM_Header}
 */
proto.commands.TLM_Header.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimeNs(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTopicType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTopicName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.commands.TLM_Header.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.commands.TLM_Header.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.commands.TLM_Header} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.TLM_Header.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimeNs();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getTopicType();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTopicName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional uint64 time_ns = 1;
 * @return {number}
 */
proto.commands.TLM_Header.prototype.getTimeNs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.commands.TLM_Header} returns this
 */
proto.commands.TLM_Header.prototype.setTimeNs = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string topic_type = 2;
 * @return {string}
 */
proto.commands.TLM_Header.prototype.getTopicType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.commands.TLM_Header} returns this
 */
proto.commands.TLM_Header.prototype.setTopicType = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string topic_name = 3;
 * @return {string}
 */
proto.commands.TLM_Header.prototype.getTopicName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.commands.TLM_Header} returns this
 */
proto.commands.TLM_Header.prototype.setTopicName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.commands.TLM_Payload.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.commands.TLM_Payload.VariantCase = {
  VARIANT_NOT_SET: 0,
  CMD_RESPONSE_PAYLOAD: 1,
  HK_PAYLOAD: 2,
  FULL_STATE_ESTIMATE: 3
};

/**
 * @return {proto.commands.TLM_Payload.VariantCase}
 */
proto.commands.TLM_Payload.prototype.getVariantCase = function() {
  return /** @type {proto.commands.TLM_Payload.VariantCase} */(jspb.Message.computeOneofCase(this, proto.commands.TLM_Payload.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.commands.TLM_Payload.prototype.toObject = function(opt_includeInstance) {
  return proto.commands.TLM_Payload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.commands.TLM_Payload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.TLM_Payload.toObject = function(includeInstance, msg) {
  var f, obj = {
    cmdResponsePayload: (f = msg.getCmdResponsePayload()) && proto.commands.CMD_Response.toObject(includeInstance, f),
    hkPayload: (f = msg.getHkPayload()) && proto.commands.TLM_HK.toObject(includeInstance, f),
    fullStateEstimate: (f = msg.getFullStateEstimate()) && proto.commands.FullStateEstimate.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.commands.TLM_Payload}
 */
proto.commands.TLM_Payload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.commands.TLM_Payload;
  return proto.commands.TLM_Payload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.commands.TLM_Payload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.commands.TLM_Payload}
 */
proto.commands.TLM_Payload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.commands.CMD_Response;
      reader.readMessage(value,proto.commands.CMD_Response.deserializeBinaryFromReader);
      msg.setCmdResponsePayload(value);
      break;
    case 2:
      var value = new proto.commands.TLM_HK;
      reader.readMessage(value,proto.commands.TLM_HK.deserializeBinaryFromReader);
      msg.setHkPayload(value);
      break;
    case 3:
      var value = new proto.commands.FullStateEstimate;
      reader.readMessage(value,proto.commands.FullStateEstimate.deserializeBinaryFromReader);
      msg.setFullStateEstimate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.commands.TLM_Payload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.commands.TLM_Payload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.commands.TLM_Payload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.TLM_Payload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCmdResponsePayload();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.commands.CMD_Response.serializeBinaryToWriter
    );
  }
  f = message.getHkPayload();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.commands.TLM_HK.serializeBinaryToWriter
    );
  }
  f = message.getFullStateEstimate();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.commands.FullStateEstimate.serializeBinaryToWriter
    );
  }
};


/**
 * optional CMD_Response cmd_response_payload = 1;
 * @return {?proto.commands.CMD_Response}
 */
proto.commands.TLM_Payload.prototype.getCmdResponsePayload = function() {
  return /** @type{?proto.commands.CMD_Response} */ (
    jspb.Message.getWrapperField(this, proto.commands.CMD_Response, 1));
};


/**
 * @param {?proto.commands.CMD_Response|undefined} value
 * @return {!proto.commands.TLM_Payload} returns this
*/
proto.commands.TLM_Payload.prototype.setCmdResponsePayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.commands.TLM_Payload.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.commands.TLM_Payload} returns this
 */
proto.commands.TLM_Payload.prototype.clearCmdResponsePayload = function() {
  return this.setCmdResponsePayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.commands.TLM_Payload.prototype.hasCmdResponsePayload = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TLM_HK hk_payload = 2;
 * @return {?proto.commands.TLM_HK}
 */
proto.commands.TLM_Payload.prototype.getHkPayload = function() {
  return /** @type{?proto.commands.TLM_HK} */ (
    jspb.Message.getWrapperField(this, proto.commands.TLM_HK, 2));
};


/**
 * @param {?proto.commands.TLM_HK|undefined} value
 * @return {!proto.commands.TLM_Payload} returns this
*/
proto.commands.TLM_Payload.prototype.setHkPayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.commands.TLM_Payload.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.commands.TLM_Payload} returns this
 */
proto.commands.TLM_Payload.prototype.clearHkPayload = function() {
  return this.setHkPayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.commands.TLM_Payload.prototype.hasHkPayload = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional FullStateEstimate full_state_estimate = 3;
 * @return {?proto.commands.FullStateEstimate}
 */
proto.commands.TLM_Payload.prototype.getFullStateEstimate = function() {
  return /** @type{?proto.commands.FullStateEstimate} */ (
    jspb.Message.getWrapperField(this, proto.commands.FullStateEstimate, 3));
};


/**
 * @param {?proto.commands.FullStateEstimate|undefined} value
 * @return {!proto.commands.TLM_Payload} returns this
*/
proto.commands.TLM_Payload.prototype.setFullStateEstimate = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.commands.TLM_Payload.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.commands.TLM_Payload} returns this
 */
proto.commands.TLM_Payload.prototype.clearFullStateEstimate = function() {
  return this.setFullStateEstimate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.commands.TLM_Payload.prototype.hasFullStateEstimate = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.commands.TLM_Holder.prototype.toObject = function(opt_includeInstance) {
  return proto.commands.TLM_Holder.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.commands.TLM_Holder} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.TLM_Holder.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && proto.commands.TLM_Header.toObject(includeInstance, f),
    payload: (f = msg.getPayload()) && google_protobuf_any_pb.Any.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.commands.TLM_Holder}
 */
proto.commands.TLM_Holder.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.commands.TLM_Holder;
  return proto.commands.TLM_Holder.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.commands.TLM_Holder} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.commands.TLM_Holder}
 */
proto.commands.TLM_Holder.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.commands.TLM_Header;
      reader.readMessage(value,proto.commands.TLM_Header.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setPayload(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.commands.TLM_Holder.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.commands.TLM_Holder.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.commands.TLM_Holder} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.commands.TLM_Holder.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.commands.TLM_Header.serializeBinaryToWriter
    );
  }
  f = message.getPayload();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
};


/**
 * optional TLM_Header header = 1;
 * @return {?proto.commands.TLM_Header}
 */
proto.commands.TLM_Holder.prototype.getHeader = function() {
  return /** @type{?proto.commands.TLM_Header} */ (
    jspb.Message.getWrapperField(this, proto.commands.TLM_Header, 1));
};


/**
 * @param {?proto.commands.TLM_Header|undefined} value
 * @return {!proto.commands.TLM_Holder} returns this
*/
proto.commands.TLM_Holder.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.commands.TLM_Holder} returns this
 */
proto.commands.TLM_Holder.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.commands.TLM_Holder.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Any payload = 2;
 * @return {?proto.google.protobuf.Any}
 */
proto.commands.TLM_Holder.prototype.getPayload = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 2));
};


/**
 * @param {?proto.google.protobuf.Any|undefined} value
 * @return {!proto.commands.TLM_Holder} returns this
*/
proto.commands.TLM_Holder.prototype.setPayload = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.commands.TLM_Holder} returns this
 */
proto.commands.TLM_Holder.prototype.clearPayload = function() {
  return this.setPayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.commands.TLM_Holder.prototype.hasPayload = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.commands);
